version: '3.9'

services:
  # Nextcloud FPM
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '9000'
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud123
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
    volumes:
      - app_data:/var/www/html
    depends_on:
      - db
    networks:
      - nextcloud-net

  # PostgreSQL interno
  db:
    container_name: nextcloud-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nextcloud-net

  # OnlyOffice Document Server
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=Systemtet2025@@
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - nextcloud-net

  # Nginx
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
    depends_on:
      - app
    networks:
      - nextcloud-net

# Volúmenes persistentes
volumes:
  app_data:
  db_data:
  document_data:
  document_log:

# Red Docker
networks:
  nextcloud-net:
    driver: bridge
